// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qaG4POt6KxVPA8Pm3gPTxKUfTtg99OU',
    appId: '1:578595838339:web:e06d81b690e1b58f17beb6',
    messagingSenderId: '578595838339',
    projectId: 'eventplanningapp-4bad5',
    authDomain: 'eventplanningapp-4bad5.firebaseapp.com',
    storageBucket: 'eventplanningapp-4bad5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKoy0BhAIpRd5aRZV3vYCssnAqBnHYa2w',
    appId: '1:578595838339:android:30bbd30f7bf272bb17beb6',
    messagingSenderId: '578595838339',
    projectId: 'eventplanningapp-4bad5',
    storageBucket: 'eventplanningapp-4bad5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE9Xy0KN2sF93yXvcSZMYy2j9FpUYIYPg',
    appId: '1:578595838339:ios:a0a6d3aebba4c4d617beb6',
    messagingSenderId: '578595838339',
    projectId: 'eventplanningapp-4bad5',
    storageBucket: 'eventplanningapp-4bad5.firebasestorage.app',
    iosBundleId: 'com.vision.eventplanningapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4qaG4POt6KxVPA8Pm3gPTxKUfTtg99OU',
    appId: '1:578595838339:web:cdbb3dfb5d7f35c117beb6',
    messagingSenderId: '578595838339',
    projectId: 'eventplanningapp-4bad5',
    authDomain: 'eventplanningapp-4bad5.firebaseapp.com',
    storageBucket: 'eventplanningapp-4bad5.firebasestorage.app',
  );
}
